# Generated by Django 4.2.5 on 2023-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='date',
            field=models.DateField(default='2022-10-06', verbose_name='birthday'),
            preserve_default=False,
        ),
    ]
