# Generated by Django 4.2.5 on 2023-09-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_birthday_options'),
        ('main_app', '0002_photo'),
    ]

    operations = [
    ]
