# Generated by Django 4.2.5 on 2023-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_birthday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideas', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='birthday',
            name='ideas',
            field=models.ManyToManyField(to='main_app.giftideas'),
        ),
    ]
