# Generated by Django 4.2.5 on 2023-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_giftideas_birthday_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
