# Generated by Django 4.1.2 on 2023-09-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_0002_alter_birthday_options_0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'ordering': ['date']},
        ),
    ]
