# Generated by Django 4.2.5 on 2023-09-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_birthday_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='delivery_method',
            new_name='notes',
        ),
    ]
