# Generated by Django 4.2.5 on 2023-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_birthday_address_alter_birthday_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftideas',
            name='ideas',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
