# Generated by Django 4.2.5 on 2023-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_giftideas_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='alert',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='delivery_method',
            field=models.TextField(blank=True, default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='email',
            field=models.CharField(blank=True, default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='ideas',
            field=models.ManyToManyField(blank=True, to='main_app.giftideas'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='phone_number',
            field=models.CharField(blank=True, default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthday',
            name='relationship',
            field=models.CharField(blank=True, default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftideas',
            name='ideas',
            field=models.TextField(blank=True, default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
