# Generated by Django 4.2.5 on 2023-09-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_birthday_address_alter_birthday_alert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
