# Generated by Django 4.2.5 on 2023-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_birthday_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='alert',
            field=models.CharField(blank=True, default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
