# Generated by Django 4.2.5 on 2023-09-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_birthday_alert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiftIdeas',
            new_name='GiftIdea',
        ),
    ]
